In [1]:
from __future__ import print_function
import torch

In [2]:
print('Ex 1')
a = 'hello'
print(a)

print('--------------------------------------------------')

Ex 1
hello
--------------------------------------------------


In [3]:
print('Ex 2')
b = {}
b[1] = a
print(b)

print('--------------------------------------------------')

Ex 2
{1: 'hello'}
--------------------------------------------------


In [6]:
print('Ex 3')
b[2] = 30
for i in range(1, len(b.keys()) + 1):
    print(b[i])

print('--------------------------------------------------')


Ex 3
hello
30
--------------------------------------------------


In [14]:
print('Ex 4')
a = torch.Tensor(5, 3)
a = torch.rand(5, 3)
print(a)

print('--------------------------------------------------')

Ex 4

 0.0426  0.0513  0.6391
 0.1882  0.6581  0.2038
 0.1025  0.8669  0.2065
 0.7203  0.8847  0.9176
 0.7606  0.1261  0.6598
[torch.FloatTensor of size 5x3]

--------------------------------------------------


In [18]:
import numpy as np

print('Ex 5')
b = torch.rand(3, 4)
c = torch.mm(a, b)
print(c)

a = a.numpy()
b = b.numpy()

c = np.matmul(a, b)
print(c)

Ex 5

 0.3448  0.4293  0.4607  0.4367
 0.6112  0.3226  0.7943  0.4690
 0.6945  0.3167  0.9529  0.4797
 1.3776  1.0604  1.6452  1.3460
 0.8089  0.7968  0.8124  0.9687
[torch.FloatTensor of size 5x4]

[[ 0.34478685  0.4293448   0.46068189  0.43667829]
 [ 0.6111778   0.32263523  0.79432499  0.46902001]
 [ 0.694516    0.31673971  0.95287251  0.47969797]
 [ 1.37755454  1.06036878  1.64516222  1.34598625]
 [ 0.80888855  0.79684997  0.81243622  0.96870917]]


In [21]:
print('Ex 6')
print(torch.cuda.is_available())
a = torch.rand(5, 3).cuda()
b = torch.rand(3, 4).cuda()
c = torch.mm(a, b)

print(c)


Ex 6
True

 0.5132  0.3164  0.5761  0.2897
 0.4768  0.4316  0.9820  0.7647
 0.6259  0.3781  0.7363  0.3901
 0.4924  0.4519  0.9746  0.7467
 0.9221  0.4773  1.0087  0.4881
[torch.cuda.FloatTensor of size 5x4 (GPU 0)]

